### ISSUE TITLE
Noob looking for a simple answer

### ISSUE THREAD

**Issue by SimplePotato** [idoco/intergram#117]
Hi.

I have only experience with static sites and servers are out of my scope. 

I thought I can only copy /paste this code before the closing tag of a page.  and everything will work.
`<script> window.intergramId = "SUPER_SECRET_CHAT_ID_ stored as a repository secret" </script>
<script id="intergram" type="text/javascript" src="https://www.intergram.xyz/js/widget.js"></script>`

While I was building a website locally, the chat worked fine. But now that I hosted the website to GitHub pages, the messages don't go through.

**Comment by mkrasselt1** [comment]
Press F12 and look for console - and present any error you might find :) -+(or just link the page directly here and I will have a look)

**Comment by SimplePotato** [comment]
Thanks @mkrasselt 
this is the page [klopca.si](https://klopca.si)
