### ISSUE TITLE
widget in full size window desktop

### ISSUE THREAD

**Issue by alexpseletr** [idoco/intergram#15]
How do I resize the widget? In my page it covers the entire window and I could not install on the server itself (shared) to make the necessary changes

**Comment by idoco** [comment]
Hi, this sounds like a bug.
Can you please attach some screen shots and other details (like screen resolution) .

Right now I use a very simplistic way to decide to open the chat on full screen -
```javascript
window.screen.height < 800
```
It might be useful to make this configurable (or use a more elegant way)

**Comment by alexpseletr** [comment]
thanks for helping
        
        Follow the attached photos, please do not put it on the
          web
        
        I will leave the page available for about 1 hour, more
          than any client can open and this generates a complaint to me
          ...
        
        If you can include in the text of the message a
          name and preferably the domain would be good ... I have to use
          your server because mine does not accept the port 3000
        
        Sorry, I do not speak English well, I used the
          translator
    
    
    
    Em 03-04-2017 13:13, Ido Cohen
      escreveu:
    
    
      Hi, this sounds like a bug.
        Can you please attach some screen shots and other details (like
        screen resolution) .
      Right now I use a very simplistic way to decide to open the
        chat on full screen -
      
        window.screen.height < 800
      
      It might be useful to make this configurable (or use a more
        elegant way)
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/idoco/intergram","title":"idoco/intergram","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/idoco/intergram"}},"updates":{"snippets":[{"icon":"PERSON","message":"@idoco in #15: Hi, this sounds like a bug.\r\nCan you please attach some screen shots and other details (like screen resolution) .\r\n\r\nRight now I use a very simplistic way to decide to open the chat on full screen -\r\n```javascript\r\nwindow.screen.height \u003c 800\r\n```\r\nIt might be useful to make this configurable (or use a more elegant way) "}],"action":{"name":"View Issue","url":"https://github.com/idoco/intergram/issues/15#issuecomment-291192077"}}}

**Comment by idoco** [comment]
Hi, I didn't get your screenshot.
If you want you can email it to me to ‘ido.mapchat at gmail.com‘

What is your screen resolution?

**Comment by idoco** [comment]
Hi @alexpseletr , The problem seems to be with the way I identify mobile devices, and since your screen hight is less than `800px` the chat is being rendered for you in mobile mode.

I will change the criteria for identifying mobile devices to  -
```javascript
window.screen.width < 500
```
And that should fix it.

Thanks for the feedback!

**Comment by idoco** [comment]
Fixed.
You might need to wait several hours or clear your browser cache for the change to take effect.
Please re-open if you still see the issue.

**Comment by alexpseletr** [comment]
solved
    
    
    Em 04-04-2017 09:09, Ido Cohen
      escreveu:
    
    
      Fixed.
        You might need to wait several hours or clear your browser cache
        for the change to take effect.
        Please re-open if you still see the issue.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/idoco/intergram","title":"idoco/intergram","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/idoco/intergram"}},"updates":{"snippets":[{"icon":"PERSON","message":"@idoco in #15: Fixed.\r\nYou might need to wait several hours or clear your browser cache for the change to take effect.\r\nPlease re-open if you still see the issue. "}],"action":{"name":"View Issue","url":"https://github.com/idoco/intergram/issues/15#issuecomment-291480370"}}}

**Comment by filipenanclarez** [comment]
I have the similar issue. On my celphone, i can't see the entire chat using materializedcss fixed nav bar (http://materializecss.com/navbar.html).
I use the follow code:

  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <a href="#!" class="brand-logo">Logo</a>
        <ul class="right hide-on-med-and-down">
          <li><a href="sass.html">Sass</a></li>
          <li><a href="badges.html">Components</a></li>
        </ul>
      </div>
    </nav>
  </div>

So in my moto g cell phone, the Welcome Message is hidden by fixed navbar.

Can I open the chat in another window ? Can I resize the window of widget on mobile ?

Thanks for your attention ...

Regards
