### ISSUE TITLE
How to add the requester name

### ISSUE THREAD

**Issue by teopost** [idoco/intergram#26]
I use intergram into an autenticated website.
I know the username of the requester.
Can I add this information to chat ? 
Now I don't recognize who call me

**Comment by idoco** [comment]
Hi @teopost , yes actually I just added a way to do it, but haven't documented it yet.
You can set this global parameter - `window.intergramOnOpen.visitorName` with the email of the logged in user and it will be passed to the chat once the chat window opens.
Tell me if that works for you an I will close the issue.

**Comment by teopost** [comment]
Sorry, but don't work.
Unfortunately I can set username only later (after "onload" page).

**Comment by idoco** [comment]
Intersting.
The value is checked and passed into the inner chat iframe only after you click to open the chat widget (hence the name `intergramOnOpen`) So It should still work if you open the chat dialog only after the user logged in and you set the `visitorName` value. 

Can you please double check that?

**Comment by teopost** [comment]
I do some extra tests.

**Comment by diegox80** [comment]
Insert in your html
`<script>
    window.intergramOnOpen = {};
    window.intergramOnOpen.visitorName='THE VISITOR NAME';
</script>`

Thanks @idoco !!

**Comment by enzojimenez** [comment]
Yes, you have to define the var window.intergramOnOpen first. Then add the visitorName
