### ISSUE TITLE
How to change the operator name

### ISSUE THREAD

**Issue by net-split** [idoco/intergram#27]
By default Intergram displays your first name in Telegram to the user on the other end. 
Is there a possibility to override this name?

(by forwarding a variable, not changing the actual script)

**Comment by idoco** [comment]
Hi @net-split , right now you can override the name by using this trick - 
1. Create a Telegram group and name it as you want your name to appear in the chat. 
2. Add the `@IntergramBot` to the group, hit `/start` and use that chat ID (including the minus sign) in the injection script.

note: when the bot is added to a group the only why to respond to visitor messages is replying to them directly in Telegram (click the incoming message and select reply)

**Comment by net-split** [comment]
Many thanks, that is super cool!
I wasn't even aware Intergram works with groups.
