### ISSUE TITLE
I can't control the click event on the widget, jQuery incompatibility?

### ISSUE THREAD

**Issue by chseluv** [idoco/intergram#40]
Hello, first of all I love this project and thanks a lot for your work.

I would like to emulate the click of a user so that when they click on specific anchor tags around the page the intergram widget pops up. I keep getting jQuery related issues if I use

`document.getElementById("intergramRoot").click()` and any other method to address that node gives me the same jQuery error in JS console. It reads "Empty string passed to getElementById".

If I test in Chrome I don't get any console error but nothing happens either at element.click()

jQuery version: 1.12.4

**Comment by idoco** [comment]
Hi @chseluv, I think it is just matter of selecting the right element to click on.
This `document.getElementById("intergramRoot").children[0].children[0].click()` works for me.

It might be a good idea to add an id to this element so it will be easier to select it.

**Comment by chseluv** [comment]
Thank you so much, it worked!

**Comment by idoco** [comment]
Great!
