### ISSUE TITLE
Is it possible to work with it if Telegram is blocked?

### ISSUE THREAD

**Issue by mirkhamidov** [idoco/intergram#47]
In Russia, Telegram servers are blocked. 
But my server is in other country, so, if some one from russia will come to my site and try to send message, will it work?

**Comment by idoco** [comment]
Hi @mirkhamidov. It should work. 

The flow is-
`Intergram web chat <-> Intergram bot server <-> Telegram API server <-> Telegram client (mobile/web)`

So if the bot server is not blocked from the visitor location, and it can communicate with the Telegram API, everything will work.

**Comment by mirkhamidov** [comment]
I got it already. I forked your project, rebuild it with my changes (I remove all mentions about telegram and your project for security reasons, if you dont mind) and deployed it in Heroku, so, thanks for your project ))

**Comment by idoco** [comment]
Great to hear that it is working for you.

Usually I ask users to keep the link to the Intergram GitHub project visible, but this sounds like a good reason to make an exception.

**Comment by mirkhamidov** [comment]
tnx
