### ISSUE TITLE
Some messages align to wrong side!

### ISSUE THREAD

**Issue by mahmoudmy** [idoco/intergram#5]
![integram](https://cloud.githubusercontent.com/assets/5320237/23153367/5f96dd4c-f81d-11e6-91cb-f8aca12c0488.png)

**Comment by mahmoudmy** [comment]
Oh, I think it's because of message length :(

**Comment by idoco** [comment]
@mahmoudmy  yeah, but it is still a bug. I should limit the max length of the message box so it's alignment will stay visible. 

Thanks for reporting.

**Comment by idoco** [comment]
Should be fix after the cached css will expire.
