### ISSUE TITLE
cannot input token telegram

### ISSUE THREAD

**Issue by amudy17** [idoco/intergram#50]
dear ido cohen,

may you advise me, i can not input the token API Telegram to script Intergram in self hosting , how to fix it ? i mean if i inputed it will show error in heroku

.post('https://api.telegram.org/bot' + process.env.------794:AAE4dk66D5OPqHXg0fu2XcvQAFYq4-bIqTg + '/sendMessage')

**Comment by amudy17** [comment]
please help the chat id is not shown also

**Comment by idoco** [comment]
Hi @amudy17

It looks like you changed it in the code itself.

When using Heroku, you can pass the api token using their environment configuration UI.

**Comment by amudy17** [comment]
thanks bro, i have success set token from bash script.
