### ISSUE TITLE
Is it possible to allow supergroup to publish

### ISSUE THREAD

**Issue by ranrinc** [idoco/intergram#58]
Need to allow intergram into my supergroup.. Showing the conversations from our website? Any ideas how?

**Comment by idoco** [comment]
Hi @ranrinc Intergram works with regular Telegram groups, but it was never tested with supergroups.  It might take a very small change in [server.js](https://github.com/idoco/intergram/blob/master/server.js#L16) to make it work.

**Comment by holographix** [comment]
any news on this topic?
I'd need to have the messages from the bot posted over a channel.
I've read a few issues and followed along:
1. Create a group
2. Add the admins
3. Add the bot

but never the less all the messages that arrive to the bot are not posted over the channel.. any suggestion?

**Comment by idoco** [comment]
Did you use the ID you got from the bot in the injection script on your website? (Including the minus sign `-` in the beginning)
