### ISSUE TITLE
Can't deploy Intergram on a HTTPS server

### ISSUE THREAD

**Issue by acidrums4** [idoco/intergram#59]
I'm trying to deploy Intergram on a (self-signed?) Let's Encrypt'ed HTTPS server.

I can successfully launch the intergram demo from HTTP (http://<public-server-ip>:3000/) and it's working, but if I try HTTPS (https://<public-server-ip>:3000/) it returns a ERR_CONNECTION_CLOSED.

Actually I need the HTTPS thing because I'm trying to deploy it on a website (located on the same server) which is served through HTTPS. Calling Intergram scripts from said website will also throw the ERR_CONNECTION_CLOSED error.

I'm a total noob about node.js so I don't know how to do that. I looked around in Google but I couldn't find some clue - I'm guessing changes should be made on server.js file, but I don't even know where to start.

**Comment by acidrums4** [comment]
Solved - It was matter of linking the .key and .crt files from the server into the server.js script and changing the server to HTTPS.

So you can include at the first line of your server.js

    const fs = require('fs') // Required for reading the certificate and key files
    let options = { key: fs.readFileSync("key.pem"), cert: fs.readFileSync("cert.crt") };

And edit the http declaring line to

    const http = require ('https').Server(options,app);

**Comment by idoco** [comment]
Good point! Do you want to add this to the readme file?

**Comment by acidrums4** [comment]
> Good point! Do you want to add this to the readme file?

Done, I guess. Closing :)
