### ISSUE TITLE
Custom text

### ISSUE THREAD

**Issue by kiliankoe** [idoco/intergram#6]
Hi,

love the project idea. I don't quite understand the project structure however. Is there are way for me to host only the frontend js so that I can customize the default text, especially the first message that is sent back to the user. 
The page I'd love to throw this is hosted via GitHub pages, so it's static only.

Thanks! 😊

**Comment by idoco** [comment]
Basically you can clone this repo, edit the UI as you want and still point it to my bot server.
If you set this [line](https://github.com/idoco/intergram/blob/master/src/chat/chat.js#L23) to point to my server. smothing like this should work -
```javascript
this.socket = io.connect('www.intergram.xyz');
``` 

But I think I should make everything more Customizable.  So what do you think about supplying the intro message as an optional variable in the injection script? (and maybe the main color also?)
```html
<script> 
  window.intergramId = <Your unique chat ID>
  window.intergramIntoMessage = "This is ZomboCom! And welcome to you, who have come to ZomboCom."
  window.intergramMainColor = "#FA8072"
</script>
```

**Comment by kiliankoe** [comment]
That would be fantastic! I'd love if it if I were able to specify any of the hardcoded messages and the color :) Will try out self-hosting the js though, thanks for the tip! :)

**Comment by idoco** [comment]
You can now customize all texts and the main color, see customization part in the readme file

**Comment by kiliankoe** [comment]
Awesome, thank you! Just tried it out and works like a charm 😊
