### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by SukhmanpreetSingh** [idoco/intergram#60]
How can i show another name than my telegram username to my users
![capture](https://user-images.githubusercontent.com/33250386/47219999-155de980-d3ce-11e8-886e-f48ff83d3e9c.PNG)

here i want to shows something other than sukhmanpreet singh

**Comment by idoco** [comment]
Hi @SukhmanpreetSingh, you can do that by creating a Telegram group and adding the bot to it. The name that will be displayed in the chat will be the name of the group.

Note that when in a group you have to directly reply to the bot's messages to respond to the visitors.

Let me know if that works for you and I will close the issue.

**Comment by SukhmanpreetSingh** [comment]
Oh Thanks To You!!
WE are from a religious ngo ur service will help us a lot
