### ISSUE TITLE
How to keep the chat open all time?

### ISSUE THREAD

**Issue by rodolfomarques** [idoco/intergram#68]
Hi!! I really liked this project, and I want to use it in a website as the main contact, replacing a typical form. Is it possible to keep the chat window always open? 

Thanks

**Comment by idoco** [comment]
Hi @rodolfomarques , keeping the chat window open at all times will create substantial load on the server.

Today, only when the chat window is opened, a new WebSocket connection is initiated to the server, waiting to transmit the visitor messages. Doing this for every visitor, even for those who don't need the chat, will force the server to maintain a huge number of active connections.
