### ISSUE TITLE
Hide/unhide floating button without page refresh

### ISSUE THREAD

**Issue by xewonder** [idoco/intergram#86]
Hello,

We are considering using the great program in oder to provide support to users on our wifi hotspot pages.

We want to hide the icon until someone "clicks" a "support button", otherwise we will just get spamed!

We do not want to refresh the page because the user login detail will "vanish".

Is it possible?

Thank you in advance

**Comment by idoco** [comment]
Hi @xewonder, sorry I didn't get to respond to your email faster, but It's always better to share these discussions on GitHub anyway.

A slightly hacky solution I can think of, is adding the Intergram script tag dynamically after a button is clicked.

```html
<button onclick="addIntergram()">
  ask for help button
</button>

<script>
  function addIntergram(src) {
    var s = document.createElement('script');
    s.setAttribute('id', "intergram");
    s.setAttribute('src', "https://www.intergram.xyz/js/widget.js");
    document.body.appendChild(s);
    
    // Intergram is waiting for a load event
    // we need to wait for the script to load before dispatching it
    setTimeout(function() {dispatchEvent(new Event('load'))}, 200);
  }
</script>
```

See the full example here - https://jsfiddle.net/0tc5k82d/

Let me know If that works for you so we can close this issue.

**Comment by xewonder** [comment]
FANTASTIC!

Thank you Ido!!!

Works perfect!
