### ISSUE TITLE
Cannot send messages with odd number of unescaped underscores

### ISSUE THREAD

**Issue by fhtagn** [idoco/intergram#9]
Cannot send messages with odd number of unescaped underscores.
Underscores can be escaped with \\

input -> output
\_text\_ -> _text_
\_\_ ->
\_\_\_\_ ->
\_text\_\_\_ -> _text_
\_text\_\\\_ -> _text_\_

This is acceptable, if _ are to be taken as formatting. However, the following inputs send no message at all:
\_d\_\_
\_werwerwer
qwerwqeqwe\_

And, in particular, intergram can't be used to share a lot of wikipedia URLs without escaping the \_. Namely, https://en.wikipedia.org/wiki/Astroid#Metric_properties

Tested in Windows 10 (Firefox, Chrome and Edge) and Android (cyanogen browser and Firefox).
Issue happens when sending from the client. Sending from Telegram always works.

**Comment by idoco** [comment]
Good catch! 
since visitors' messages have unexpected content they should never be parsed as markdown.
See #10
