### ISSUE TITLE
All replies from Telegram are send to all chat clients

### ISSUE THREAD

**Issue by adriaanvanrossum** [idoco/intergram#91]
I think this is very bad in the current code of the this app.

If you reply from Telegram the websocket will send to all chats that reply.

**Comment by idoco** [comment]
If you reply directly to a specific message, only that visitor will receive that response.

This is also the default mode when adding the bot to a group.

You can quite easily fork this repository and change this default behavior for your website.

**Comment by adriaanvanrossum** [comment]
I mean all messages end up at all chat clients. Meaning if you have 5 active users using your chat feature and you response to one of them the other users can access those messages when they inspect the web socket. Do you have a demo running somewhere? Would love to show the bug.

**Comment by anubra266** [comment]
@idoco This should be implemented please.

**Comment by idoco** [comment]
Thanks @adriaanvanrossum this requires immediate fixing.

This will need a slightly bigger refactor than just replacing io with the connection. 
In the code section you linked to, I will need to get the right connection (socket) to send the message to. 
maybe I can manage a map between `chatId + "-" + userId` and the relevant socket, and emit only to that socket.

If someone is willing to help with this, I'd love to merge their changes

**Comment by anubra266** [comment]
I couldn't work on this project. Most of the dependencies wanted an old version of NodeJs. And majority of my projects use newer versions. Is this suppose to happen?

**Comment by adriaanvanrossum** [comment]
Maybe this can be of help.

Here the code buffers the message when user is not online: https://github.com/squarecat/squarechat/commit/8d0f3ba42984ed082737cafe46afd4cb803b00ef#diff-78c12f5adc1848d13b1c6f07055d996e
And here they use part of that code to send to only one socket: https://github.com/squarecat/squarechat/commit/918ed1f7f7dac7edd518a64f2e6fb2ecbd81e0fc

**Comment by Jivings** [comment]
Let me know if you want me to submit https://github.com/squarecat/squarechat/commit/918ed1f7f7dac7edd518a64f2e6fb2ecbd81e0fc as a PR since I think it alone fixes the most serious issue.

**Comment by adriaanvanrossum** [comment]
Isn't this issue super important @idoco?

**Comment by idoco** [comment]
This should be fixed now. Please review the fix [here](https://github.com/idoco/intergram/commit/dde08760520d21e348238c3d9770f3245c545599).

The proposed solution didn't work because we don't have the socket in context when the message is sent from the admin back to the client.

Sorry for the delay. But without external help, it takes me a long time to sit down and fix complex issues.

**Comment by adriaanvanrossum** [comment]
Glad you figured it out! Thanks for solving this issue for future users. 🙏
