### ISSUE TITLE
Adding property for "You" visitor name

### ISSUE THREAD

**Issue by NFKData** [idoco/intergram#99]
As the code is implemented, "You" prefix is controlled like that:

```Javascript
if (from === 'visitor') {
    name = "You";
}
```

But it could controlled by something like that:
```Javascript
if (from === 'visitor') {
    name = props.conf.visitorMessageName;
}
```

I could do the change and open a PR if this feature is wanted.

**Comment by idoco** [comment]
Sure. Create a PR and I will review and merge it.
Please leave `"You"` as the default pronoun for users who don't use `props.conf.visitorPronoun`

**Comment by NFKData** [comment]
Closing as the PR is already merged!
